[package]
name = "firefly"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16"
bitflags = "2.10.0"
bytemuck = "1.24.0"
fixedbitset = "0.5.7"

[dev-dependencies]
rand = "0.9.2"
iyes_perf_ui = "0.5"